GSA-TTS/identity-idva-monitoring

Procfile
manifest.yaml
prometheus.yml
setup.sh
vars.yaml

Deploys Prometheus in cloud.gov, configured to just monitor itself. Nothing fancy.

Set up basic Prometheus deployment

---

prometheus-config.yml

- Remove outdated and superfluous comments
- Add dns_sd_config entry for monitoring-dash app

add monitoring dash

---

manifest.yaml

- Remove duplicate manifest code from monitoring

split deployments

---

.github/workflows/deploy.yaml

- Update prometheus to v2.28.0
- Fix memory misallocation by specifying --memory and --instances flags

correct memory misallocation

---

.github/workflows/deploy.yaml

- Use cf setup action in deployment
- Add release trigger for deploy workflow

use cf setup action

---

.github/workflows/README.md
.github/workflows/deploy.yaml
README.md
manifest-alerts.yaml
manifest.yaml
prometheus-config.yml

Please ensure all references to 'GIVE' have been addressed.

Change project name to IDVA

---

alerts/alert-config.yml
rules.yml

- Update rule descriptions and remove superfluous uses of the word app
- Change channel-name to match new idva channel
- Print alert summary and description in slack message
- Print environment of affected application in slack text

update rules details

---

rules.yml

- Modify rules expressions to show 5 minute average
- Add alarms on 0% average hardware utilization
- Add alerting rules to satisfy SSP

create ssp alerts

---

prometheus/install_prometheus.sh

Bump Prometheus version from 2.30.0 -> 2.30.1

Bump Prometheus version from 2.30.0 -> 2.30.1

---

.github/workflows/deploy.yaml
grafana/conf/custom.ini
grafana/conf/provisioning/dashboards/idva-dashboards.yaml
grafana/conf/provisioning/datasources/prometheus.yaml
grafana/dashboards/hardware_dashboard.json
grafana/dashboards/kong_dashboard.json
grafana/install_grafana.sh
grafana/manifest.yml

- Include Grafana project files
- Update deployment action to include Grafana

include grafana

---

.github/workflows/deploy.yaml
README.md
alertmanager/manifest.yaml
grafana/manifest.yaml
prometheus/manifest.yaml
prometheus/prometheus-config.yml

- Update resource names in manifest files
- Update Prometheus config to use new route names
- Update network polices to use new app names
- Add brief descriptions for available tools
- Update Kong scrape job

improve naming

---

.github/workflows/deploy-kibana.yaml
kibana/.cfignore
kibana/apt.yml
kibana/config/kibana.yml
kibana/manifest.yaml
kibana/vars.yaml

Deploy Kibana to enable monitoring and querying flow logs.

Deploy kibana

---

.cfignore
.github/workflows/update.yaml
prometheus/.cfignore

- Change jq command in update action to use -r raw option to remove quotes
- Move  cfignore file into app folder so that is detected by cf comand

fix jq command to use option raw

---

.github/workflows/deploy.yaml
grafana/dashboards/elasticsearch-dashboard.json
prometheus/prometheus-config.yml

Add elasticsearch metrics and dashboard

Add elasticsearch metrics and dashboard

---

.cfignore
.github/workflows/update.yaml
version_updater.sh

- Add repo owner condition
- Change reviewers to idva-partners
- Remove script duplication in workflows

Improve update workflow

---

prometheus/rules.yml

Remove "No X Utilization" rules.

remove no utilization rules

---

prometheus/prometheus-config.yml

- Add Alertmanager scrape job
- Add Cortex scrape job

add scrape targets

---

prometheus/rules.yml

Alert for Redis key size
alert for es shard count
alert for es disk space

Alerts for Redis and Elasticsearch

---

.github/workflows/check-config.yaml
prometheus/rules.yml

- Rename duplicate rule disk utilization rulename
- Add rules.yml trigger for check-config workflow

correct rules file

---

watchtower/config.yaml

- Add internal route for Kibana
- Update route for outbound proxy
- Add flow-client app config
- Add keycloak app config

update watchtower config

---

.github/workflows/deploy-idvametrics.yaml
idvametrics/analyticsquery.py
idvametrics/analyticsutils.py
idvametrics/login.py
idvametrics/main.py
idvametrics/manifest.yaml
idvametrics/requirements.txt

Some environments in Ping require multi-factor authentication to login and obtain flow data. This PR adds support for MFA for the required environments while still allowing for simple login into environments that do not require MFA.

Support mfa in script

---

create-network-policies.sh
idvametrics/login.py
idvametrics/manifest.yaml

Resolves issues with deployment of the `idvametrics` app and ensure 200 status codes are returned during authentications.

Resolve Deployment Issues

---

watchtower/config.yaml

Updating to add apps and routes that have changed recently.

Update Watchtower config with new apps and routes

---

alertmanager/manifest.yaml
grafana/conf/custom.ini
grafana/conf/provisioning/datasources/prometheus.yaml
prometheus/manifest.yaml
prometheus/prometheus-config.yml

- Add grafana reverse proxy settings
- Add Prometheus reverse proxy settings
- Add sub-path to Alertmanager

monitoring reverse proxy settings

---

.github/workflows/python-black.yaml
idvametrics/analyticsquery.py

- Fix formatting with Black formatter
- Add GitHub action to format Python with Black

Enforce Black formatting for Python

---

.github/workflows/deploy-cron.yaml
cron/crontab
cron/manifest.yaml

Do not merge until [Analytics API](https://github.com/GSA-TTS/identity-idva-gdrive/pull/73) has been merged.

Adding a POST request to run analytics  daily
