- create_web_config.sh
- manifest.yaml
Use the Cloud Foundry Instance Identity Credentials (see
https://docs.cloudfoundry.org/devguide/deploy-apps/instance-identity.html)
to enable operating the Prometheus server using HTTPS instead
of HTTP.
> Add web-config file for HTTPS setup

- alertmanager/alert-config.yml
Modifies the alerting config to send alerts to a new #idva-alerts channel specifically for the
monitoring/alerting system notifications. GitHub secret containing the slack webhook has
also been updated to reflect the new URL.
> Switch alert config to use new idva-alerts channel

- .github/workflows/check-config.yaml
- .github/workflows/deploy.yaml
Currently, the config check is doing nothing. It worked at one point, but the repo structure and workflow has changed since then and the github actions weren't updated to match. It is currently set to trigger on the wrong file, and even then it's only checking the Prometheus configuration. The changes here will correct the workflows and add validation for Alertmanager configs via the `amtool` provided with Alertmanager.
- Fix file name for config validation check
- Add step to generate config before validtion
- Add config validation for alertmanager config
- Generate config files before usage
- Include validation for alertmanager config file
> fix config check

- prometheus/prometheus-config.yml
This repo started using Prometheus with a config file that set the
scrape_interval and evaluation_interval to 15s each. The value was
chosen without much forethought, and hasn't been re-evaluated since.
By setting these values back to their defaults (1m), we get the
following benefits:
1) 75% reduction in data generated by Prometheus.
2) 75% reduction in network activity generated by Prometheus
This should result in much less storage and overall pressure on the
monitoring system. The only expected and valid question left to
answer is "will this affect our monitoring since we aren't evaluating
as often?". Each of our rules defined in rules.yml are either
aggregating data over the last 5m or are using another method to alert.
This means that we don't currently have any rules that would …
> Remove custom scrape and evaluation intervals

- prometheus/install_prometheus.sh
[Prometheus 2.30.2 release](https://github.com/prometheus/prometheus/releases/tag/v2.30.2)
> Bump Prometheus version from 2.30.1 -> 2.30.2

- .github/workflows/check-config.yaml
- .github/workflows/deploy.yaml
To prevent duplication of the config validation action code, a workflow
can and should reference the existing workflow within the repository.
See https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
> Use local workflow reference to prevent duplication

- .github/workflows/deploy.yaml
- Remove outdated comment
- Use rolling deployment strategy for Alertmanager
- Deploy alertmanager prior to Prometheus
> correct deployment order

- .github/workflows/deploy.yaml
- prometheus/apt.yml
- prometheus/manifest.yaml
- prometheus/prometheus-config.yml
- Add apt buildpack to install envsubst
- Move config generation within manifest command
- Add external labels to support long-term storage
Following the [Cortex documentation](https://cortexmetrics.io/docs/guides/ha-pair-handling/#client-side),
this PR will add two external labels to our metric data. The "__replica__" label is required to be unique in order
to de-duplicate incoming metric streams so I've relied on the CF_INSTANCE_INDEX environment variable to
accomplish this. That change in turn required changing where the 'envsubst' command is run, changing from
our actions pipeline, to the manifest file.
Existing config-validation being done in GitHub Actions should be unaffected by this change.
> add external labels

- alertmanager/alert-config.yml
- prometheus/prometheus-config.yml
- prometheus/rules.yml
This alert formatting differs from the norm. By disabling aggregation, each slack message can be known to contain only a single alert, simplifying message formatting in exchange for potentially more messages.
Sample:
> Improve alerts formating

- alertmanager/manifest.yaml
- prometheus/manifest.yaml
Add external urls to alertmanager and prometheus. In combination with an appropriate hosts file, this will allow links in the alert messages to work correctly
> Add external urls to alertmanager and prometheus.

- cortex/manifest.yaml
- prometheus/prometheus-config.yml
- Fix cortex route to match naming standard for monitoring apps
- Correct Cortex URL in prometheus remote-write config section
> correct route name

- .github/workflows/update.yaml
Making the bot the author of the commit for the update flow slightly improves the appearance of the commit and removes the partial verification issue on commits.
> Set bot as commit author for update flow

- version_updater.sh
The check for monotonically increasing versions address the issue where a patch release is made to an older minor version. This change will prevent that update from triggering a PR
> check to make sure versions are monotonically increasing

- .github/workflows/deploy-grafana.yaml
- .github/workflows/deploy-prometheus.yaml
- grafana/manifest.yaml
- prometheus/create_web_config.sh
- prometheus/manifest.yaml
- prometheus/run.sh
- prometheus/web-config-template.yml
- Download Prometheus files prior to cf deployment
- Download Grafana files prior to cf deployment
- Move install to separate action step
This update moves the installation process for IDVA monitoring tools from within the cloud.gov environment to their respective GitHub Actions run. This will prevent deployments from failing when IDVA switches to controlled-egress spaces within cloud.gov.
The following tools will be in public-egress spaces and thus do not need their installation processes installed:
* Cortex: Relies on reaching S3, which currently has to be done via a public-egress space
* Alertmanager: Sends alerts to public notification endpoints
* Watchtower: Queries the public Cloud.gov API endpoints
> download files in cicd

- prometheus/prometheus-config.yml
Removal of the "instance" label should solve the issue of multiple
alerts coming in for apps where multiple instances are running. IDVA
does not, nor should it ever, rely on the IP addresses found in the
"instance" label when deciding whether or not to send an alert. Dropping
this label when sending alerts to alertmanager allows us to receive
fewer alerts while preserving the data in Prometheus should teams need
to troubleshoot and identify problematic app instances.
> Remove "instance" label from alert labels

- watchtower/.profile
Add support to use a forward proxy by using a `.profile` cf initialization script. Does nothing if not bound to the `outbound-proxy` user-provided service.
> Add proxy support via .profile initalization script

- prometheus/rules.yml
In order to compensate for cloud foundry automatically restarting,
restaging, and deployment of applications, extending the duration of the
"job down" alert to 5m gives any application five minutes to have
all instances come back online before deeming a Prometheus scrape job as
down.
> Extend duration of "job down" alert rule

- .github/workflows/deploy-es.yaml
- .github/workflows/deploy-redis.yaml
Similar to other deployment workflows, do not initiate deployments on changes to markdown files.
> Ignore deployment triggers on changes to markdown files

- create-network-policies.sh
- grafana/conf/custom.ini
- grafana/manifest.yaml
- prometheus/prometheus-config.yml
Switching to usage of the cloud.gov `61443` port, which includes the SAN
for cloud.gov apps, allows connecting to Grafana via fully-valid TLS connections.
- Use http health check for Grafana
- Remove direct instance identity cert usage
- Switch to using https port for Grafana
> grafana use cloud gov cert

- cortex/config.yaml
- create-network-policies.sh
- prometheus/prometheus-config.yml
- redis/manifest.yaml
- Switch to using https port for Watchtower
- Switch to using https port for Cortex
- Switch to using https port for ES exporter
- Switch to using https port for Redis exporter
> monitoring use cloud gov cert

- create-network-policies.sh
- grafana/conf/provisioning/datasources/cortex.yaml
- Correct port used to contact the Cortex datasource
- Update Grafana->Cortex network policy
> correct cortex datasource port

- create-network-policies.sh
- elasticsearch/manifest.yaml
- kibana/config/kibana.yml
Both the Elasticsearch Prometheus exporter and the Kibana app within
IDVA use the es-proxy to support aws sigV4 signing. By switching to
connecting via https over 61443 we better protect all information
over those connections.
> Switch to cloud.gov https port for es-proxy

- elasticsearch/manifest.yaml
Over the period from March 11, 2022 10:00AM to March 18, 2022 10:00 AM
there were an average of 8.8 timeout errors per hour from the ES
exporter ("context deadline exceeded (Client.Timeout exceeded while
awaiting headers)".
By SSH'ing into the es exporter and performing curl requests to the same
endpoint as the exporter, we can see that the requests do take a few
seconds to execute, but they always seem to finish if given enough time.
By increasing the timeout settings for the exporter via the "es.timeout"
CLI flag, the average has dropped to ~1 per hour (based only on a couple
of hours worth of data, rather than a week). Estimated reduction of
timeout errors will be around 9-10X.
> Increase ES exporter timeout setting

- alertmanager/create_web_config.sh
- alertmanager/manifest.yaml
- create-network-policies.sh
- prometheus/prometheus-config.yml
Configures traffic from Prometheus to Alertmanager to use the cloud.gov certificates
over 61443 that include the app SAN. This change also necessitated changing the
service discovery type for Alermanager to a static_config, since the SAN on the cloud.gov
cert does not include individual IP addresses (which is what Prometheus will use for
alerts instead of a DNS entry for dns_sd_configs).
- Configure Prometheus to use Cloud.gov https port
- Remove usage of instance identity certs for alertmanager
- Change prometheus -> alertmanager port in network policies
> alertmanager use cloud gov certs

- prometheus/prometheus-config.yml
Correction of URL for Alertmanager that was modified during the testing process of #170
> Fix url for Alertmanager that was altered during testing

- prometheus/prometheus-config.yml
All the necessary certificates and network policies are already in place to perform full validation of this connection. Remove the old configuration specifying to skip validation.
> Remove insecure_skip_verify configuration for cf-metrics scrape

- kibana/config/kibana.yml
- kibana/manifest.yaml
- add internal route to kibana
- configure ca for es proxy cert to allow kibana to tls to connect to es
- configure kibana to be accessible over https
> Kibana tls configuration

- .github/workflows/deploy-alertmanager.yaml
- .github/workflows/deploy-cortex.yaml
- .github/workflows/deploy-es.yaml
- .github/workflows/deploy-grafana.yaml
- .github/workflows/deploy-kibana.yaml
- .github/workflows/deploy-prometheus.yaml
- .github/workflows/deploy-watchtower.yaml
- create-network-policies.sh
- watchtower/.profile
- watchtower/manifest.yaml
- Improve .profile proxy initialization
- Add environment_name variable to network policy setup
- Add outbound-proxy to service bindings
- Move Watchtower installation outside of Cloud.gov
- Add multi-space support to network policy creation
> watchtower use outbound proxy

- alertmanager/create_tls_config.sh
- alertmanager/manifest.yaml
Version 0.24.0 of Alertmanager now provides (albeit experimental)
support for TLS with the cluster gossip traffic. We can start taking
advantage of this feature by creating the TLS config and populating it
with the CF Instance Identity certs that are available on the
application instnces since these certs will contain the app IP SAN. See
https://docs.cloudfoundry.org/devguide/deploy-apps/instance-identity.html
> Enable TLS for Alertmanger gossip traffic

- create-network-policies.sh
Change the network policy for Kong to target the `closed` space.
> Update network policy to Kong to reflect new space deployment

- .github/workflows/deploy-alertmanager.yaml
- .github/workflows/deploy-cortex.yaml
- .github/workflows/deploy-es.yaml
- .github/workflows/deploy-grafana.yaml
- .github/workflows/deploy-prometheus.yaml
- alertmanager/manifest.yaml
- cortex/manifest.yaml
- create-network-policies.sh
- elasticsearch/manifest.yaml
- kibana/manifest.yaml
- Move alertmanager to public egress space
- Move Cortex install into GitHub Action
- Move Grafana to a closed-egress space type
- Move Prometheus to closed-egress space type
- Move ElasticSearch exporter to closed-egress space type
- Simplify kibana manifest.yaml
- Add spacing to improve network policy script readability
> restrict egress

- idvametrics/main.py
Currently, we do not have the necessary data in the analytics index to differentiate where a user is in a flow when they reach a point of verification. That information is contained in the `outcomeType` property, which needs to be written into analytics documents for use in Kibana.
> Upload additional data to pass rate document

- .github/workflows/deploy-cortex.yaml
- create-network-policies.sh
Because Cortex is unable to access S3 due to space egress control limitations, we are moving it to a public-egress space.
> Move Cortex to public space for S3 access

- grafana/conf/custom.ini
The IDVA team has never made its Grafana instance publicly accessible,
and the use of basic auth was simply because it was there. The Grafana
application is already protected by the standard GSA authentication
mechanisms and requires MFA. We are removing basic auth as it
contributes little to the overall security posture of the service and
reduces the number of secrets required for the IVDA team to manage.
> Remove basic auth
